import { auth, getOrders, onAuthStateChanged, signInWithEmailAndPassword, signOut, subscribeToOrders, updateOrderStatus } from './firebase-config.js';

const statuses = ['new', 'confirmed', 'preparing', 'out-for-delivery', 'delivered', 'cancelled'];
const statusLabels = { new: 'New', confirmed: 'Confirmed', preparing: 'Preparing', 'out-for-delivery': 'Out for Delivery', delivered: 'Delivered', cancelled: 'Cancelled' };
let orders = [];
let stopOrders = null;
let firstSnapshot = true;

const $ = selector => document.querySelector(selector);
const esc = value => String(value ?? '').replace(/[&<>"']/g, character => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[character]));
const orderDate = order => order.orderDate ? new Date(order.orderDate) : (order.createdAt?.toDate ? order.createdAt.toDate() : null);
const money = value => `${Number(value || 0).toLocaleString('en-US')} EGP`;
const statusKey = value => statuses.includes(value) ? value : 'new';

function isAdmin(user) {
  return user?.getIdTokenResult ? user.getIdTokenResult().then(token => token.claims.admin === true) : Promise.resolve(false);
}
function showLoginError(message) { const status = $('#adminLoginStatus'); if (status) status.textContent = message; }

function initLogin() {
  onAuthStateChanged(auth, async user => { if (user && await isAdmin(user)) location.href = '/admin/dashboard/'; });
  $('#adminLoginForm')?.addEventListener('submit', async event => {
    event.preventDefault(); showLoginError('Signing in...');
    try { const credential = await signInWithEmailAndPassword(auth, $('#adminEmail').value.trim(), $('#adminPassword').value); if (!(await isAdmin(credential.user))) { await signOut(auth); throw new Error('not-admin'); } location.href = '/admin/dashboard/'; }
    catch (error) { showLoginError(error.message === 'not-admin' ? 'This account does not have administrator access.' : 'Unable to sign in. Check your email and password.'); }
  });
}

function initDashboard() {
  onAuthStateChanged(auth, async user => {
    if (!user || !(await isAdmin(user))) { await signOut(auth).catch(() => {}); location.href = '/admin/login/'; return; }
    $('#adminEmailLabel').textContent = user.email || 'Admin';
    stopOrders = subscribeToOrders(snapshot => {
      const incoming = snapshot.docChanges().some(change => change.type === 'added' && !firstSnapshot);
      orders = snapshot.docs.map(item => ({ id: item.id, ...item.data() })); firstSnapshot = false;
      if (incoming) { notifyNewOrder(); toast('New order received'); }
      render();
    }, () => { $('#adminContent').innerHTML = '<div class="empty-state">Unable to read orders. Check your Firestore Security Rules.</div>'; });
  });
  bindShell();
}
function bindShell() {
  $('#adminLogout')?.addEventListener('click', () => signOut(auth));
  $('#openSidebar')?.addEventListener('click', () => $('#adminSidebar').classList.add('open'));
  $('#closeSidebar')?.addEventListener('click', () => $('#adminSidebar').classList.remove('open'));
  $('#refreshButton')?.addEventListener('click', async () => { orders = await getOrders(); render(); toast('Orders refreshed'); });
  $('#closeOrderModal')?.addEventListener('click', closeModal);
  $('#orderModal')?.addEventListener('click', event => { if (event.target.id === 'orderModal') closeModal(); });
}
function currentView() { return new URLSearchParams(location.search).get('view') || (location.pathname.includes('/orders') ? 'orders' : location.pathname.includes('/products') ? 'products' : location.pathname.includes('/customers') ? 'customers' : location.pathname.includes('/analytics') ? 'analytics' : location.pathname.includes('/settings') ? 'settings' : 'dashboard'); }
function render() {
  const view = currentView(); document.querySelectorAll('.admin-nav a').forEach(link => link.classList.toggle('active', link.dataset.view === view));
  const title = { dashboard: 'Good morning, Admin', orders: 'Orders', products: 'Products', customers: 'Customers', analytics: 'Analytics', settings: 'Settings' }[view]; $('#pageTitle').textContent = title; $('#breadcrumb').textContent = view.toUpperCase();
  ({ dashboard: renderDashboard, orders: renderOrders, products: renderProducts, customers: renderCustomers, analytics: renderAnalytics, settings: renderSettings }[view])();
}
function stats() { const today = new Date(); const sameDay = order => { const date = orderDate(order); return date && date.toDateString() === today.toDateString(); }; return { total: orders.length, pending: orders.filter(order => !['delivered', 'cancelled'].includes(statusKey(order.status))).length, today: orders.filter(sameDay).length, revenue: orders.filter(sameDay).reduce((sum, order) => sum + Number(order.totals?.total || 0), 0) }; }
function statMarkup(data) { return `<div class="stats-grid"><div class="stat-card"><p>Total Orders</p><strong>${data.total}</strong><small>All recorded orders</small></div><div class="stat-card"><p>Pending Orders</p><strong>${data.pending}</strong><small>Needs attention</small></div><div class="stat-card"><p>Orders Today</p><strong>${data.today}</strong><small>Live from Firestore</small></div><div class="stat-card"><p>Today's Revenue</p><strong>${money(data.revenue)}</strong><small>Before refunds</small></div></div>`; }
function renderDashboard() { const data = stats(); $('#adminContent').innerHTML = `${statMarkup(data)}<div class="surface"><div class="section-title"><h3>Recent orders</h3><a class="back-link" href="/admin/orders/">View all →</a></div>${ordersMarkup(orders.slice(0, 8))}</div>`; }
function filtersMarkup() { return `<div class="filters"><input class="filter-input" id="orderSearch" placeholder="Search order ID, customer, or phone" /><select class="filter-select" id="statusFilter"><option value="">All statuses</option>${statuses.map(status => `<option value="${status}">${statusLabels[status]}</option>`).join('')}</select><select class="filter-select" id="paymentFilter"><option value="">All payments</option><option value="cash">Cash on Delivery</option><option value="vodafone_cash">Vodafone Cash</option></select><select class="filter-select" id="dateFilter"><option value="">Any date</option><option value="today">Today</option><option value="yesterday">Yesterday</option><option value="week">This week</option><option value="month">This month</option></select></div>`; }
function renderOrders() { $('#adminContent').innerHTML = `<div class="page-heading"><div><h2>Orders</h2><p>Every order is synced live from the existing Firestore collection.</p></div></div>${filtersMarkup()}<div class="surface" id="ordersSurface">${ordersMarkup(orders)}</div>`; ['orderSearch', 'statusFilter', 'paymentFilter', 'dateFilter'].forEach(id => $(`#${id}`).addEventListener('input', filterOrders)); }
function filterOrders() { const text = $('#orderSearch').value.toLowerCase(); const status = $('#statusFilter').value; const payment = $('#paymentFilter').value; const date = $('#dateFilter').value; const now = new Date(); const filtered = orders.filter(order => { const created = orderDate(order); const haystack = `${order.id} ${order.customer?.name || ''} ${order.customer?.phone || ''}`.toLowerCase(); let dateMatch = true; if (created && date === 'today') dateMatch = created.toDateString() === now.toDateString(); if (created && date === 'yesterday') { const yesterday = new Date(now); yesterday.setDate(now.getDate() - 1); dateMatch = created.toDateString() === yesterday.toDateString(); } if (created && date === 'week') dateMatch = now - created < 7 * 86400000; if (created && date === 'month') dateMatch = created.getMonth() === now.getMonth() && created.getFullYear() === now.getFullYear(); return haystack.includes(text) && (!status || statusKey(order.status) === status) && (!payment || order.payment?.method === payment) && dateMatch; }); $('#ordersSurface').innerHTML = ordersMarkup(filtered); }
function ordersMarkup(list) { if (!list.length) return '<div class="empty-state">No orders match this view.</div>'; return `<div class="table-wrap"><table class="data-table"><thead><tr><th>Order</th><th>Customer</th><th>Items</th><th>Total</th><th>Payment</th><th>Date / time</th><th>Status</th></tr></thead><tbody>${list.map(order => `<tr data-order-id="${esc(order.id)}"><td><span class="order-id">#${esc(order.id.slice(0, 8))}</span></td><td><b>${esc(order.customer?.name || 'Guest')}</b><br><span class="muted">${esc(order.customer?.phone || 'No phone')}</span></td><td>${(order.items || []).reduce((sum, item) => sum + Number(item.quantity || 0), 0)} items</td><td><b>${money(order.totals?.total)}</b></td><td>${order.payment?.method === 'vodafone_cash' ? 'Vodafone Cash' : 'Cash'}</td><td>${formatDate(order)}</td><td><span class="status-badge status-${statusKey(order.status)}">${statusLabels[statusKey(order.status)]}</span></td></tr>`).join('')}</tbody></table></div>`; }
function formatDate(order) { const date = orderDate(order); return date ? `${date.toLocaleDateString('en-GB')}<br><span class="muted">${date.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</span>` : '<span class="muted">Pending timestamp</span>'; }
function renderProducts() { $('#adminContent').innerHTML = `<div class="page-heading"><div><h2>Products</h2><p>Menu source inspection</p></div></div><div class="product-notice">The current customer menu is stored in <b>data/menu-data.js</b>, not Firestore. No Firebase product collection exists in this repository, so product CRUD is intentionally unavailable here. Adding a new collection would create a duplicate menu source and would not automatically update the customer website.</div>`; }
function customerRows() { const map = {}; orders.forEach(order => { const phone = order.customer?.phone || 'Unknown'; const customer = map[phone] ||= { name: order.customer?.name || 'Guest', phone, orders: 0, spent: 0, last: orderDate(order), address: order.delivery?.address || '' }; customer.orders++; customer.spent += Number(order.totals?.total || 0); if (orderDate(order) > customer.last) { customer.last = orderDate(order); customer.address = order.delivery?.address || customer.address; } }); return Object.values(map); }
function renderCustomers() { const customers = customerRows(); $('#adminContent').innerHTML = `<div class="page-heading"><div><h2>Customers</h2><p>Aggregated from existing order records. No duplicate customer records are created.</p></div></div><input class="filter-input" id="customerSearch" placeholder="Search by name or phone" style="margin-bottom:16px"/><div class="surface" id="customersSurface">${customerMarkup(customers)}</div>`; $('#customerSearch').addEventListener('input', event => { const value = event.target.value.toLowerCase(); $('#customersSurface').innerHTML = customerMarkup(customers.filter(customer => `${customer.name} ${customer.phone}`.toLowerCase().includes(value))); }); }
function customerMarkup(customers) { if (!customers.length) return '<div class="empty-state">No customer data yet.</div>'; return `<div class="table-wrap"><table class="data-table"><thead><tr><th>Customer</th><th>Orders</th><th>Total spent</th><th>Last order</th><th>Address</th></tr></thead><tbody>${customers.map(customer => `<tr><td><b>${esc(customer.name)}</b><br><span class="muted">${esc(customer.phone)}</span></td><td>${customer.orders}</td><td>${money(customer.spent)}</td><td>${customer.last ? customer.last.toLocaleDateString('en-GB') : '-'}</td><td>${esc(customer.address || '-')}</td></tr>`).join('')}</tbody></table></div>`; }
function renderAnalytics() { const data = stats(); const productMap = {}; orders.forEach(order => (order.items || []).forEach(item => { productMap[item.name] = (productMap[item.name] || 0) + Number(item.quantity || 0); })); const best = Object.entries(productMap).sort((a, b) => b[1] - a[1]).slice(0, 8); const max = best[0]?.[1] || 1; const ranges = [1, 7, 30].map(days => orders.filter(order => { const date = orderDate(order); return date && Date.now() - date.getTime() < days * 86400000; })); $('#adminContent').innerHTML = `<div class="page-heading"><div><h2>Analytics</h2><p>Calculated from ${orders.length} real orders in Firestore.</p></div></div><div class="stats-grid"><div class="stat-card"><p>Orders today</p><strong>${data.today}</strong></div><div class="stat-card"><p>Orders this week</p><strong>${ranges[1].length}</strong></div><div class="stat-card"><p>Orders this month</p><strong>${ranges[2].length}</strong></div><div class="stat-card"><p>Average order value</p><strong>${money(orders.length ? orders.reduce((sum, order) => sum + Number(order.totals?.total || 0), 0) / orders.length : 0)}</strong></div></div><div class="chart-grid"><div class="surface"><div class="section-title"><h3>Best selling products</h3></div><div class="bar-chart">${best.length ? best.map(([name, count]) => `<div class="bar" style="height:${Math.max(8, count / max * 100)}%"><span>${count} · ${esc(name)}</span></div>`).join('') : '<div class="empty-state">No item data yet.</div>'}</div></div><div class="surface"><div class="section-title"><h3>Revenue by period</h3></div><div class="settings-list">${[['Today', 1], ['This week', 7], ['This month', 30]].map(([label, days]) => { const total = orders.filter(order => { const date = orderDate(order); return date && Date.now() - date.getTime() < days * 86400000; }).reduce((sum, order) => sum + Number(order.totals?.total || 0), 0); return `<div><span>${label}</span><b>${money(total)}</b></div>`; }).join('')}</div></div></div>`; }
function renderSettings() { $('#adminContent').innerHTML = `<div class="page-heading"><div><h2>Settings</h2><p>Environment and integration details</p></div></div><div class="surface settings-list"><div><span>Firebase project</span><b>bumble-burger</b></div><div><span>Orders collection</span><b>orders</b></div><div><span>Authentication</span><b>Email and password</b></div><div><span>Admin authorization</span><b>Custom claim: admin = true</b></div></div>`; }
function openOrder(orderId) { const order = orders.find(item => item.id === orderId); if (!order) return; $('#orderModalContent').innerHTML = `<p class="eyebrow">ORDER DETAILS</p><h2 id="orderModalTitle">#${esc(order.id)}</h2><div class="detail-grid"><div class="detail-block"><b>Customer</b><span>${esc(order.customer?.name || 'Guest')} · ${esc(order.customer?.phone || '-')}</span></div><div class="detail-block"><b>Delivery address</b><span>${esc(order.delivery?.areaName || '')} ${esc(order.delivery?.address || '-')}</span></div><div class="detail-block"><b>Date / time</b><span>${formatDate(order)}</span></div></div><div class="surface"><div class="section-title"><h3>Products</h3><b>${money(order.totals?.total)}</b></div>${(order.items || []).map(item => `<div class="settings-list"><div><span>${esc(item.name)} × ${item.quantity}</span><b>${money(Number(item.price) * Number(item.quantity))}</b></div></div>`).join('')}<div class="settings-list"><div><span>Subtotal</span><b>${money(order.totals?.subtotal)}</b></div><div><span>Delivery fee</span><b>${money(order.totals?.delivery)}</b></div><div><span>Payment</span><b>${order.payment?.method === 'vodafone_cash' ? 'Vodafone Cash' : 'Cash on Delivery'}</b></div></div></div><div class="modal-actions">${statuses.map(status => `<button data-status="${status}" class="${statusKey(order.status) === status ? 'selected' : ''}">${statusLabels[status]}</button>`).join('')}</div>`; $('#orderModal').hidden = false; $('#orderModalContent').querySelectorAll('[data-status]').forEach(button => button.addEventListener('click', () => changeStatus(order.id, button.dataset.status))); }
async function changeStatus(orderId, status) { try { await updateOrderStatus(orderId, status); const order = orders.find(item => item.id === orderId); if (order) order.status = status; closeModal(); render(); toast(`Order marked ${statusLabels[status]}`); } catch { toast('Status update failed'); } }
function closeModal() { $('#orderModal').hidden = true; }
function toast(message) { const element = $('#toast'); element.textContent = message; element.classList.add('show'); setTimeout(() => element.classList.remove('show'), 2600); }
function notifyNewOrder() { try { const context = new AudioContext(); const oscillator = context.createOscillator(); const gain = context.createGain(); oscillator.connect(gain); gain.connect(context.destination); oscillator.frequency.value = 720; gain.gain.value = .05; oscillator.start(); oscillator.stop(context.currentTime + .12); } catch {} }
document.addEventListener('click', event => { const row = event.target.closest('[data-order-id]'); if (row) openOrder(row.dataset.orderId); });
if (location.pathname.includes('/login')) initLogin(); else if (location.pathname.includes('/dashboard')) initDashboard();
